### ISSUE TITLE
Silent failure when CSS file is invalid

### ISSUE THREAD

**Issue by aladage** [deg-skeletor/skeletor-plugin-postcss#5]
When a watch/build is run and a CSS file is invalid, the CSS task will run and say it successfully completed, but the CSS will not actually be compiled.

**Comment by scheul93** [comment]
Not sure if there is a lot we can do about this.

Worked with Aaron and had malformed css. Postcss plugin bundled the css however it included an `@import` statement. 

From what I can tell, the reported bug is with the postcss library and not with the plugin
